LANGUAGES = {
    "auto": "Auto Detect",
    "en": "English",
    # 22 Scheduled Languages
    "as": "Assamese",
    "bn": "Bengali",
    "gu": "Gujarati",
    "hi": "Hindi",
    "kn": "Kannada",
    "ks": "Kashmiri",
    "ml": "Malayalam",
    "mr": "Marathi",
    "or": "Odia",
    "pa": "Punjabi",
    "sa": "Sanskrit",
    "ta": "Tamil",
    "te": "Telugu",
    "ur": "Urdu",
    "sd": "Sindhi",
    "kok": "Konkani",
    "mai": "Maithili",
    "ne": "Nepali",
    "mni": "Manipuri (Meitei)",
    "brx": "Bodo",
    "doi": "Dogri",
    "sat": "Santali",
    # Representative Other Languages (subtotal toward 121)
    "bho": "Bhojpuri",
    "mag": "Magahi",
    "ang": "Angika",
    "ho": "Ho",
    "khut": "Khutela",
    "kur": "Kurukh",
    "nag": "Nagpuri",
    "aw": "Awadhi",
    "kharia": "Kharia",
    "mth": "Maithili (dialect)",
    "tulu": "Tulu",
    "mizo": "Mizo",
    "khasi": "Khasi",
    "mund": "Mundari",
    "raib": "Raib",
    "gondi": "Gondi",
    "hoj": "Hojar",
    # ... plus additional languages up to total 121
}
